### ISSUE TITLE
spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by pandey21197** [bamlab/flashlight#103]
<img width="1412" alt="Screenshot 2023-05-05 at 12 33 30 PM" src="https://user-images.githubusercontent.com/100587075/236395707-a7b69bf2-38ea-4155-b32a-ba8cbab2629b.png">

getting this issue when trying to start measuring

**Comment by pandey21197** [comment]
<img width="567" alt="Screenshot 2023-05-05 at 3 31 54 PM" src="https://user-images.githubusercontent.com/100587075/236429723-d87bac22-c9d0-49c1-b211-f55873da5313.png">


> Hi @pandey21197, thanks for reporting!
> 
> Can you check if there's a process called `atrace` running on the device by running `ps | grep "adb shell"` in the terminal?
> 
> If so, what happens if you try to run `adb shell atrace --async_stop` before starting in Flipper?

**Comment by pandey21197** [comment]
@Almouro Tried everything not able to resolve this. Can you please help here.

**Comment by Almouro** [comment]
@pandey21197m you made a typo, the command was using `atrace` not `atrice` 😉 

Hopefully that fixes it, if not we should release a new version quite soon that fixes similar issues, so might do the trick

**Comment by hannojg** [comment]
Hey @Almouro, I am running into the same issue.

- There is no process called trace running on the device
- Running `adb shell atrace --async_stop` makes no difference unfortunately

**Comment by tichopad** [comment]
Hey guys!

I'm having the same exact issue when running Flashlight via CLI as well. Version 0.7.1. Both Linux and macOS.

Running
```bash
flashlight test \
  --bundleId com.my.app \
  --beforeAllCommand "maestro test sign-in.yaml" \
  --testCommand "maestro test basic-flow.yaml" \
  --duration 200000 \
  --iterationCount  5 \
  --resultsFilePath results.json
```

Randomly fails on ENOBUFS error.

Reducing `--duration` seems to help, although that might be a red herring.
Can confirm that `adb shell` process is running.

Running `adb shell atrace --async_stop` also helps.

**Comment by Almouro** [comment]
Hi @tichopad, thanks for this! Reproducing via CLI will be useful.
Would you be able to share the full logs of the crash? 🙏

**Comment by tichopad** [comment]
Sure thing!

<details>
  <summary>Here's a terminal output from macOS</summary>
  <pre>
  [12:10:48] ℹ️  Installing C++ profiler for arm64-v8a architecture
[12:10:49] ✅  C++ Profiler installed in /data/local/tmp/BAMPerfProfiler
/snapshot/flashlight-serverless/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

<ref *1> Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:814:24)
    at Object.execSync (node:child_process:894:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at executeCommand (/snapshot/flashlight-serverless/node_modules/@perf-profiler/profiler/dist/src/commands/shell.js:8:45)
    at startATrace (/snapshot/flashlight-serverless/node_modules/@perf-profiler/profiler/dist/src/commands/cppProfiler.js:25:32)
    at ensureCppProfilerIsInstalled (/snapshot/flashlight-serverless/node_modules/@perf-profiler/profiler/dist/src/commands/cppProfiler.js:62:9)
    at new PerformanceTester (/snapshot/flashlight-serverless/node_modules/@perf-profiler/e2e/dist/index.js)
    at /snapshot/flashlight-serverless/node_modules/@perf-profiler/e2e/dist/index.js
    at Generator.next (<anonymous>) {
  errno: -55,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [ '-c', 'adb shell atrace --async_stop' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    Buffer(1056768) [Uint8Array] [
       32, 100, 111, 110, 101,  10,  84,  82,  65,  67,  69,  58,
       10,  35,  32, 116, 114,  97,  99, 101, 114,  58,  32, 110,
      111, 112,  10,  35,  10,  35,  32, 101, 110, 116, 114, 105,
      101, 115,  45, 105, 110,  45,  98, 117, 102, 102, 101, 114,
       47, 101, 110, 116, 114, 105, 101, 115,  45, 119, 114, 105,
      116, 116, 101, 110,  58,  32,  56,  49,  56,  53,  50,  47,
       56,  49,  56,  53,  50,  32,  32,  32,  35,  80,  58,  56,
       10,  35,  10,  35,  32,  32,  32,  32,  32,  32,  32,  32,
       32,  32,  32,  32,
      ... 1056668 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 42483,
  stdout: Buffer(1056768) [Uint8Array] [
     32, 100, 111, 110, 101,  10,  84,  82,  65,  67,  69,  58,
     10,  35,  32, 116, 114,  97,  99, 101, 114,  58,  32, 110,
    111, 112,  10,  35,  10,  35,  32, 101, 110, 116, 114, 105,
    101, 115,  45, 105, 110,  45,  98, 117, 102, 102, 101, 114,
     47, 101, 110, 116, 114, 105, 101, 115,  45, 119, 114, 105,
    116, 116, 101, 110,  58,  32,  56,  49,  56,  53,  50,  47,
     56,  49,  56,  53,  50,  32,  32,  32,  35,  80,  58,  56,
     10,  35,  10,  35,  32,  32,  32,  32,  32,  32,  32,  32,
     32,  32,  32,  32,
    ... 1056668 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}
  </pre>
</details>

Not sure if that's helpful, though. Would an output with `logLevel` set to `trace` be more useful?

**Comment by Almouro** [comment]
@tichopad that's perfect! Seems to confirm it comes from [here](https://github.com/bamlab/flashlight/blob/main/packages/android-performance-profiler/src/commands/cppProfiler.ts#L30)

I'm trying a small fix on https://github.com/bamlab/flashlight/pull/107 but can't reproduce the issue for some reason.

Would you be able to try before and after with:

```bash
git clone https://github.com/bamlab/flashlight.git
cd flashlight
git checkout fix/spawn-buffer-overflow
yarn
yarn tsc --build
# Replacing flashlight test with the local version 👇
node packages/e2e-performance/dist/bin.js test ...

# This above should hopefully succeed! Worth double-checking it does on branch main
git checkout main
yarn tsc --build
# Replacing flashlight test with the local version 👇
node packages/e2e-performance/dist/bin.js test ...
```

**Comment by tichopad** [comment]
Works! :shipit:

Thanks man, you really saved my bacon ♥️

**Comment by Almouro** [comment]
Hi @pandey21197, @hannojg, doing a bit of cleanup on Github issues, so I'm closing this one for now for lack of activity ☺️ 

I think this is fixed now, but do feel free to reopen if the problem is still there! 🙏
