### ISSUE TITLE
cannot stop build/test

### ISSUE THREAD

**Issue by sparshmartireshk** [bamlab/flashlight#112]
<img width="1429" alt="image" src="https://github.com/bamlab/flashlight/assets/117884066/826a6e9a-1a21-4c34-9c60-44bb1ba86952">
how do i stop a build

**Comment by Almouro** [comment]
Thanks for raising this @sparshmartireshk! seems like there was indeed a weird issue with this one which basically made Flashlight hang
We'll look into it 👀

**Comment by Almouro** [comment]
Issue should be fixed now, and we now have an "abort button", closing this issue then!
