### ISSUE TITLE
[Question] How to make perf comparison 

### ISSUE THREAD

**Issue by ryuever** [bamlab/flashlight#132]
I am working on boosting List performance project in my company. Then found flashlight is exactly what i want to make perf benchmark.

I have ran flashlist with my own project call `SpectrumList`. code base could be found https://github.com/red-armor/ReactNativeListComparison. It's based on the demo example https://github.com/naqvitalha/travelMate. The bench result is posted as below. In fact, I was shocked for this.

![WeChatWorkScreenshot_06d142e5-db42-424b-8e94-ef30f9b0e581](https://github.com/bamlab/flashlight/assets/2316727/54b07045-9d9a-4edf-a4eb-2880c69674b6)

And then, I has also followed your project on twitter, the following is related post link.
- https://twitter.com/almouro/status/1564227005121454081?s=20
- https://docs.flashlight.dev/examples/flashlist/report.html

The question is I want to make benchmark result more reasonable, So could you give some suggestion or any demo code base?

Best regards

**Comment by Almouro** [comment]
Hi @ryuever, we're planning to write a blog post in the coming days, exactly about how to make Flashlist/Flatlist comparison! 🥳

The gist will pretty much be:

- automating scrolling with Maestro e2e test
- running `flashlight test` (https://docs.flashlight.dev/test/maestro)
  - on app with Flatlist
  - on app with Flashlist
- checking out the report `flashlight report results1.json results2.json`

Then doing the same thing in the cloud

Stay tuned!

**Comment by ryuever** [comment]
Thanks for kind reply. Looking forward to related blog post :)

**Comment by Almouro** [comment]
And here's finally the guide I was mentioning https://www.bam.tech/article/measuring-react-native-performance-with-flashlight 🥳
