### ISSUE TITLE
how can create report with two sessions to compare between them

### ISSUE THREAD

**Issue by YOEL311** [bamlab/flashlight#133]
I see your example that your compare in the report between two session
how can I do like this

![image](https://github.com/bamlab/flashlight/assets/39925212/6f3ea747-e976-404b-8234-7332e4c43503)

Tnanks

**Comment by Almouro** [comment]
Hi @YOEL311, are you using Flashlight locally or in the cloud?

## Local use
You need to extract a `json` of the results (either with `flashlight test` or downloading the results from `flashlight measure`/Flipper)
Then you can compare => https://docs.flashlight.dev/report/comparison

## Cloud use

There's not a great way to do it yet, but we're working on it!

There is a manual hacky way to do it though if you're curious:

If you know your test ids you can already see the comparison report by changing the url manually:

https://app.flashlight.dev/report?testRunIds=ID_1&testRunIds=ID_2 (replace ID_1 and ID_2 in the url)

You can find your test id by going to the [history section](https://app.flashlight.dev/test-list), then clicking "Show report" and checking the url

**Comment by YOEL311** [comment]
Thanks
