### ISSUE TITLE
Flashlight should offer more stats guidance (Stats, standard deviation, comparison...)

### ISSUE THREAD

**Issue by Almouro** [bamlab/flashlight#163]
# Flashlight should offer more stats guidance

Say you have the comparison below, what to do with it:

![image](https://github.com/bamlab/flashlight/assets/4534323/b00e0f67-c760-4f05-87a5-47d51fe21da7)
 
 Sure score increases, but it'd be nice to see:
 
 ## See what increased and what decreased
 
 - [x] Add in the Report summary card for comparisons the increase/decrease
 
 For instance in this case:
 - Average FPS: 54.5 (+1.7%)
 - Average CPU: 55.7% (-2.8%)
 ...
 
 We also need:
 - [ ] figure out how we handle comparisons with more than 2 results
 - [ ] add this in thread tables as well
 
 For later:
 - [ ] define a threshold on what constitute a danger or not
 - [ ] a clear recommendation with an icon/emoji for instance ✅ ❌🟰
 
 ## Standard deviation in a single run ✅
 
Done in #178 
 
 ## Standard deviation in the comparison
 
 The point here is to be able to say :
 - does my app **consistently** perform better or worse through each iteration
 
 For instance, Flashlight should be able to tell you:
 average CPU usage is down 5% and that is consistent through all iterations +/- 0.5%

**Comment by mojavad** [comment]
I'll take this 😍

**Comment by Almouro** [comment]
We now have a lot more stats in reports and in perf dashboards, closing this for now 🥳
