### ISSUE TITLE
[Question] Bitrise integration

### ISSUE THREAD

**Issue by wonderlul** [bamlab/flashlight#174]
Hello Everyone,

I was trying to integrate Flashlight with Bitrise. So I added Script step:
```
#!/usr/bin/env bash

# Install Flashlight
curl https://get.flashlight.dev/ | bash

# Export PATH
export PATH=$PATH:$HOME/.flashlight/bin

# Run Flashlight command with the correct --test path
flashlight cloud --app $BITRISE_APK_PATH --test .maestro/subflows/prepare.yaml --apiKey $FLASHLIGHT_API_KEY
```

Here are the logs:

![Screenshot 2023-11-24 at 11 04 41](https://github.com/bamlab/flashlight/assets/56554355/0827e71f-9730-4190-abe4-da92855afdb4)

Can you tell me why is this happening? Is something missing in preparation? Maestro flow that I'm trying to invoke refers to another flow from .maestro folder and it couldn't be found. I probably miss something how the code is being read by the tool.

![Screenshot 2023-11-24 at 11 11 20](https://github.com/bamlab/flashlight/assets/56554355/f88ad15a-feae-44dd-8faf-3938942a533f)
![Screenshot 2023-11-24 at 11 11 48](https://github.com/bamlab/flashlight/assets/56554355/728a3779-e468-48a9-be7e-dfbcfc2291c1)

Looking forward to hearing from you!

Best regards

**Comment by wonderlul** [comment]
Quick response: that was exactly it! The separate flow couldn't be found. So how do I reach separate flows then? Any ideas?

Thank you

**Comment by carloscba** [comment]
I have a question related to Bitrise. We've observed that CPU usage per thread differs when running the same APK triggered from Bitrise compared to running it locally.

When triggered from Bitrise, it has a score of 52, but when sent from a local environment, it has a score of 72.

Thank you

**Comment by Almouro** [comment]
Hi @carloscba!
So the score depends both on the device being used (on Flashlight Cloud, it's a low end Samsung Galaxy A10s) et the `--duration` parameter
Likely the device you're using locally has better performance

**Comment by carloscba** [comment]
Apologies for the unclear explanation. I generated two reports using Flashlight Cloud, but for the same APK, there are two different scores when the 'cloud' command is triggered from my PC or from Bitrise.

Thank you

**Comment by Almouro** [comment]
Oh right, indeed that shouldn't change the scoring then.
Can you share the urls of the reports where the scores are different?
