### ISSUE TITLE
flashlight test Error 

### ISSUE THREAD

**Issue by Lokizjj29** [bamlab/flashlight#179]
when I run the demo of Usage with Maestro

error thrown 

Error: Invalid line: 28825 (AWCN Worker(M)1) S 367 367 0 0 -1 1077936192 15 0 0 0 0 0 0 0 20 0 31 0 12492622 16141717504 35945 18446744073709551615 1 1 0 0 0 0 4608 1 1073775868 0 0 0 -1 3 0 0 0 0 0 0 0 0 0 0 0 0 0   

/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/cpu/getCpuStatsByProcess.js:24:19

suggest changing the regex in line 22 of getCpuStatsByProcess.js to "/^(\d+) \((.*)\) (.*)/"

**Comment by Almouro** [comment]
Hi @Lokizjj29, thanks for reporting this, and good catch!

Would you like to submit a pull request by any chance?
You'd have to:
- Modify https://github.com/bamlab/flashlight/blob/main/packages/platforms/android/src/commands/cpu/getCpuStatsByProcess.ts#L28
- Add a test similar to https://github.com/bamlab/flashlight/blob/main/packages/platforms/android/src/commands/cpu/__tests__/getCpuStatsByProcess.test.ts#L40

Check it works with:

```bash
yarn
yarn jest getCpuStatsByProcess
```
