### ISSUE TITLE
UI/JS FPS profiling

### ISSUE THREAD

**Issue by mizerc** [bamlab/flashlight#66]
Hello 👋🏻 ,

First, awesome work, thanks for putting the effort on this tool.

Is it possible to track both IU and JS FPS in a production build? I could find the --fps flag, but I think that is tracking only UI thread, right?

**Comment by Almouro** [comment]
Hi @mizerc, 

Thanks for the feedback!

We won't track JS FPS as reported by the RN Perf monitor, however we can get the JS thread CPU Usage which is directly correlated.

0%     JS thread CPU Usage = Max JS FPS 
100% JS thread CPU Usage = 0 JS FPS

The name of the thread in `mqt_js`. 

- If I'm using the Flipper plugin or the web reporter for instance, I can see there's a massive issue on JS side here:
![image](https://user-images.githubusercontent.com/4534323/215139340-4c9be903-bf3d-42a0-91a1-ca7657220ce2.png)

- Via the CLI, you can do `npx @perf-profiler/profiler profile --fps --threadNames "(mqt_js)"`

**Comment by Almouro** [comment]
Hi, just wrote this doc about JS performance https://docs.flashlight.dev/guides/react-native/js-fps
Closing this issue then, feel free to reopen or suggest edits to the doc if something is unclear! ☺️
