### ISSUE TITLE
Permission Denied Issue 

### ISSUE THREAD

**Issue by adhamhassan99** [bamlab/flashlight#69]
Hello everyone ,
When I try to follow the steps on my organization's laptop I get this permission error but it works fine On my laptop. I need to know what to enable exactly in order to have it work as IT removed some restrictions and It still gives this error.
```
[12:54:07] ℹ️ Appium capabilities: {"platformName":"Android","appium:automationName":"UiAutomator
2","appPackage":"com.moj","appium:noReset":true,"autoLaunch":false,"appActivity":"com.moj.MainActivity","newCommandTimeout":600000}
 architecture Installing C++ profiler for x86
[12:54:08] ✅ C++ Profiler installed in /data/local/tmp/BAMPerfProfiler
Error: Command failed: adb shell /data/local/tmp/BAMPerfProfiler printCpuClockTick
/system/bin/sh: /data/local/tmp/BAMPerfProfiler: can't execute: Permission denied
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at executeCommand (C:\Users\ahabd\Documents\EjadaProjects\MOJ\node_modules\@perf-profiler\profiler\src\commands\shell.ts:6:20)
    at retrieveCpuClockTick (C:\Users\ahabd\Documents\EjadaProjects\MOJ\node_modules\@perf-profiler\profiler\src\commands\cppProfiler.ts:82:19)
    at ensureCppProfilerIsInstalled (C:\Users\ahabd\Documents\EjadaProjects\MOJ\node_modules\@perf-profiler\profiler\src\commands\cppProfiler.ts:70:5)
    at new PerformanceTester (C:\Users\ahabd\Documents\EjadaProjects\MOJ\node_modules\@perf-profiler\e2e\src\index.ts:23:33)
    at C:\Users\ahabd\Documents\EjadaProjects\MOJ\node_modules\@perf-profiler\e2e\src\index.ts:101:18
    at Generator.next (<anonymous>)
    at C:\Users\ahabd\Documents\EjadaProjects\MOJ\node_modules\@perf-profiler\e2e\dist\index.js:8:71 {
  status: 126,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(83) [Uint8Array] [
       47, 115, 121, 115, 116, 101, 109, 47, 98, 105, 110, 47,
      115, 104, 58, 32, 47, 100, 97, 116, 97, 47, 108, 111,
       99, 97, 108, 47, 116, 109, 112, 47, 66, 65, 77, 80,
      101, 114, 102, 80, 114, 111, 102, 105, 108, 101, 114, 58,
       32, 99, 97, 110, 39, 116, 32, 101, 120, 101, 99, 117,
      116, 101, 58, 32, 80, 101, 114, 109, 105, 115, 115, 105,
      111, 110, 32, 100, 101, 110, 105, 101, 100, 13, 10
    ]
  ],
  pid: 16248,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(83) [Uint8Array] [
     47, 115, 121, 115, 116, 101, 109, 47, 98, 105, 110, 47,
    115, 104, 58, 32, 47, 100, 97, 116, 97, 47, 108, 111,
     99, 97, 108, 47, 116, 109, 112, 47, 66, 65, 77, 80,
    101, 114, 102, 80, 114, 111, 102, 105, 108, 101, 114, 58,
     32, 99, 97, 110, 39, 116, 32, 101, 120, 101, 99, 117,
    116, 101, 58, 32, 80, 101, 114, 109, 105, 115, 115, 105,
    111, 110, 32, 100, 101, 110, 105, 101, 100, 13, 10
  ]
}
```

**Comment by Almouro** [comment]
Hi @adhamhassan99, thanks for posting your issue! 🙏 

So the script has failed because it cannot run `adb shell /data/local/tmp/BAMPerfProfiler printCpuClockTick`

`adb shell` is used to run commands on your Android device
- we upload an executable called `BAMPerfProfiler` in the  `/data/local/tmp` folder on your Android device
- and then execute it with `adb shell /data/local/tmp/BAMPerfProfiler printCpuClockTick` for instance

So the issue seems to be coming from the Android device itself, the device doesn't let you run this particular executable
What phone do you have and which Android version? Is it your own or also managed by your organization?

**Comment by adhamhassan99** [comment]
Hi @Almouro , Thank you for Replying ! 
 
I tried Running `adb shell star`t and `adb shell stop`  on the emulator itself with no RN app running and it replied with `Must be root` so i ran `adb root` then I re-ran the start and stop commands it successfully started and stopped the emulator!

I am using a Pixel 6 Pro Phone using **API 30**  and **android 11.0 x86** .
And the android is on the emulator so its not managed by my organization .

Thanks for your help hoping to solve this issue with your kind assistance !

**Comment by adhamhassan99** [comment]
I also noted something very strange. When I start my script Appium opens and closes instantly on the android and the emulator makes a sound as if it rebooted . when i try to open the appium app installed on the emulator it crashes or closes automatically or crashes technically.

**Comment by Almouro** [comment]
Hi @adhamhassan99, sorry for the delay

This is quite weird, do you see anything out of the ordinary in the emulator logs? (with Android Studio log explorer or `adb logcat`)

Sometimes when I'm having trouble with Appium, I just uninstall the Appium app on the device with:
```
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test
```
and that sometimes fixes things

**Comment by adhamhassan99** [comment]
Hello @Almouro so sorry for the delayed reply I got caught up in other tasks and the thread disappeared from my feed.

I remember seeing the emulator complaining about appium but I dont have any logs for that now.

I will try the above commands when I get the chance to and Inform you about the outcome.

Again thanks for getting back to me

**Comment by Almouro** [comment]
Hi @adhamhassan99, doing a bit of cleanup on Github issues, so I'm closing this one for now for lack of activity ☺️ 

But do feel free to reopen if the problem is still there or if there are any new things to mention! 🙏
