### ISSUE TITLE
Crashing when trying to write report

### ISSUE THREAD

**Issue by JanithaR** [bamlab/flashlight#98]
I'm using version 0.3.0 on MAC

After profiling and trying to write the report I get the following exception.

> 14:33:02] ℹ️  Installing C++ profiler for arm64-v8a architecture
> [14:33:02] ✅  C++ Profiler installed in /data/local/tmp/BAMPerfProfiler
> [14:33:14] ℹ️  Writing report...
> 
> /snapshot/flashlight-serverless/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
>         throw ex;
>         ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
>     at Object.openSync (node:fs:577:10)
>     at Object.openSync (pkg/prelude/bootstrap.js:796:32)
>     at Object.writeFileSync (node:fs:2170:35)
>     at writeReport (/snapshot/flashlight-serverless/node_modules/@perf-profiler/e2e/dist/writeReport.js)
>     at /snapshot/flashlight-serverless/node_modules/@perf-profiler/e2e/dist/commands/measure/bin.js
>     at Generator.next (<anonymous>)
>     at fulfilled (/snapshot/flashlight-serverless/node_modules/@perf-profiler/e2e/dist/commands/measure/bin.js) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }

**Comment by Almouro** [comment]
Hi @JanithaR, thanks for reporting this! 🙏 

This should be fixed now in the latest `flashlight` version. If not, feel free to reopen this issue!

You can update `flashlight` by running `curl https://get.flashlight.dev/ | bash`
